version: '3.2'
services:
  app:
    build:
      context: .
    volumes:
      - ./src:/app/src
    env_file: env
    command: sleep infinity

## for testing purposes, the minio can be used.
#
#  minio:
#    image: minio/minio
#    command: ["server", "--address", ":80", "/data"]
#    environment:
#      MINIO_ACCESS_KEY: foo
#      MINIO_SECRET_KEY: bar
